
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Pirana
 */
public class SuperAdmin extends javax.swing.JFrame {

    /**
     * Creates new form SuperAdmin
     */
    public SuperAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
        setColor(jPanel4);
        Addlib_panel.setVisible(true);
        Editlib_panel.setVisible(false);
    }
    int xx;
    int xy;

    String driver = "com.mysql.jdbc.Driver";
    String url = "jdbc:mysql://localhost:3306/librarydb?zeroDateTimeBehavior=convertToNull";
    String user = "root";
    String pass = "";

    public void setColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(197, 197, 197));
    }

    public void resetColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(255, 255, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        jLabelMinimize = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Editlib_panel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Id1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Id2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Id3 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_pass1 = new javax.swing.JPasswordField();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel22 = new javax.swing.JLabel();
        txt_pass3 = new javax.swing.JPasswordField();
        jCheckBox4 = new javax.swing.JCheckBox();
        btn_update = new javax.swing.JButton();
        txt_searchid = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        Addlib_panel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        Id4 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Id5 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        Id6 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txt_pass2 = new javax.swing.JPasswordField();
        jCheckBox3 = new javax.swing.JCheckBox();
        btn_Insert1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SLTC LMS");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(887, 610));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(860, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(854, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(45, 118, 232));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("X");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });
        jPanel2.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 22, -1));

        jLabelMinimize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelMinimize.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinimize.setText("-");
        jLabelMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(818, 0, 20, -1));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Library Management System");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 210, 20));

        jPanel9.setBackground(new java.awt.Color(45, 118, 232));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel9MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel9MousePressed(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Exit_25px.png"))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Logout");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel19)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addContainerGap())
        );

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, 100, 40));

        jPanel10.setBackground(new java.awt.Color(45, 118, 232));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel10MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel10MousePressed(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Home_25px_1.png"))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Home");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 100, 40));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_User_25px.png"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel10.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Add/update Librarian");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 160, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Reading_100px.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 200));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(45, 118, 232));
        jLabel3.setText("Add Librarian");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(25, 25, 25))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 190, 50));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(45, 118, 232));
        jLabel4.setText("Edit Librarian");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel4)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(25, 25, 25))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 190, 50));

        Editlib_panel.setBackground(new java.awt.Color(255, 255, 255));
        Editlib_panel.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(45, 118, 232));
        jLabel9.setText("Username");
        Editlib_panel.add(jLabel9);
        jLabel9.setBounds(40, 60, 70, 17);

        Id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id1IdActionPerformed(evt);
            }
        });
        Editlib_panel.add(Id1);
        Id1.setBounds(150, 50, 130, 30);

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(45, 118, 232));
        jLabel11.setText("Name");
        Editlib_panel.add(jLabel11);
        jLabel11.setBounds(40, 100, 70, 17);

        Id2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id2IdActionPerformed(evt);
            }
        });
        Editlib_panel.add(Id2);
        Id2.setBounds(150, 90, 130, 30);

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(45, 118, 232));
        jLabel13.setText("Email");
        Editlib_panel.add(jLabel13);
        jLabel13.setBounds(40, 140, 80, 17);

        Id3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id3IdActionPerformed(evt);
            }
        });
        Editlib_panel.add(Id3);
        Id3.setBounds(150, 130, 130, 30);

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(45, 118, 232));
        jLabel17.setText("New Password");
        Editlib_panel.add(jLabel17);
        jLabel17.setBounds(40, 180, 90, 17);
        Editlib_panel.add(txt_pass1);
        txt_pass1.setBounds(150, 170, 120, 30);

        jCheckBox2.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(45, 118, 232));
        jCheckBox2.setText("Show Password");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2jCheckBox1ActionPerformed(evt);
            }
        });
        Editlib_panel.add(jCheckBox2);
        jCheckBox2.setBounds(280, 180, 99, 23);

        jLabel22.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(45, 118, 232));
        jLabel22.setText("Re-typePassword");
        Editlib_panel.add(jLabel22);
        jLabel22.setBounds(40, 217, 110, 20);
        Editlib_panel.add(txt_pass3);
        txt_pass3.setBounds(150, 210, 120, 30);

        jCheckBox4.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(45, 118, 232));
        jCheckBox4.setText("Show Password");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4jCheckBox1ActionPerformed(evt);
            }
        });
        Editlib_panel.add(jCheckBox4);
        jCheckBox4.setBounds(280, 213, 99, 30);

        btn_update.setBackground(new java.awt.Color(34, 167, 240));
        btn_update.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Change_User_20px.png"))); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        Editlib_panel.add(btn_update);
        btn_update.setBounds(150, 250, 93, 29);

        txt_searchid.setBorder(null);
        txt_searchid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchidActionPerformed(evt);
            }
        });
        txt_searchid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchidKeyReleased(evt);
            }
        });
        Editlib_panel.add(txt_searchid);
        txt_searchid.setBounds(110, 10, 140, 20);
        Editlib_panel.add(jSeparator1);
        jSeparator1.setBounds(120, 30, 130, 10);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Find_User_Male_30px_1.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        Editlib_panel.add(jLabel1);
        jLabel1.setBounds(260, 10, 30, 30);

        jPanel1.add(Editlib_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 380, 300));

        Addlib_panel.setBackground(new java.awt.Color(255, 255, 255));
        Addlib_panel.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(45, 118, 232));
        jLabel14.setText("Username");
        Addlib_panel.add(jLabel14);
        jLabel14.setBounds(40, 30, 70, 17);

        Id4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id4IdActionPerformed(evt);
            }
        });
        Addlib_panel.add(Id4);
        Id4.setBounds(130, 20, 130, 30);

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(45, 118, 232));
        jLabel15.setText("Name");
        Addlib_panel.add(jLabel15);
        jLabel15.setBounds(40, 70, 70, 17);

        Id5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id5IdActionPerformed(evt);
            }
        });
        Addlib_panel.add(Id5);
        Id5.setBounds(130, 60, 130, 30);

        jLabel20.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(45, 118, 232));
        jLabel20.setText("Email");
        Addlib_panel.add(jLabel20);
        jLabel20.setBounds(40, 110, 80, 17);

        Id6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id6IdActionPerformed(evt);
            }
        });
        Addlib_panel.add(Id6);
        Id6.setBounds(130, 100, 130, 30);

        jLabel21.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(45, 118, 232));
        jLabel21.setText("Password");
        Addlib_panel.add(jLabel21);
        jLabel21.setBounds(40, 150, 57, 17);
        Addlib_panel.add(txt_pass2);
        txt_pass2.setBounds(130, 140, 130, 30);

        jCheckBox3.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(45, 118, 232));
        jCheckBox3.setText("Show Password");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3jCheckBox1ActionPerformed(evt);
            }
        });
        Addlib_panel.add(jCheckBox3);
        jCheckBox3.setBounds(270, 150, 99, 23);

        btn_Insert1.setBackground(new java.awt.Color(34, 167, 240));
        btn_Insert1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btn_Insert1.setForeground(new java.awt.Color(255, 255, 255));
        btn_Insert1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Add_User_Male_20px.png"))); // NOI18N
        btn_Insert1.setText("Submit");
        btn_Insert1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Insert1ActionPerformed(evt);
            }
        });
        Addlib_panel.add(btn_Insert1);
        btn_Insert1.setBounds(100, 210, 100, 29);

        jPanel1.add(Addlib_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 380, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMousePressed

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void jPanel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseEntered
        // TODO add your handling code here:
        sColor(jPanel9);
    }//GEN-LAST:event_jPanel9MouseEntered

    private void jPanel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseExited
        // TODO add your handling code here:
        rColor(jPanel9);
    }//GEN-LAST:event_jPanel9MouseExited

    private void jPanel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MousePressed
        // TODO add your handling code here:
        //login frame
        LogIn li = new LogIn();
        li.setVisible(true);
        li.pack();
        li.setLocationRelativeTo(null);
        li.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_jPanel9MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        // TODO add your handling code here:
        setColor(jPanel4);
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        // TODO add your handling code here:
        resetColor(jPanel4);
    }//GEN-LAST:event_jPanel4MouseExited

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        // TODO add your handling code here:
        setColor(jPanel4);
        Addlib_panel.setVisible(true);
        Editlib_panel.setVisible(false);
    }//GEN-LAST:event_jPanel4MousePressed

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        // TODO add your handling code here:
        setColor(jPanel5);

    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        // TODO add your handling code here:
        resetColor(jPanel5);
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        // TODO add your handling code here:
        setColor(jPanel5);
        Addlib_panel.setVisible(false);
        Editlib_panel.setVisible(true);
    }//GEN-LAST:event_jPanel5MousePressed

    private void Id1IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id1IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id1IdActionPerformed

    private void Id2IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id2IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id2IdActionPerformed

    private void Id3IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id3IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id3IdActionPerformed

    private void jCheckBox2jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox2.isSelected()) {
            txt_pass1.setEchoChar((char) 0);

        } else {
            txt_pass1.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox2jCheckBox1ActionPerformed

    private void Id4IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id4IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id4IdActionPerformed

    private void Id5IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id5IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id5IdActionPerformed

    private void Id6IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id6IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id6IdActionPerformed

    private void jCheckBox3jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox3.isSelected()) {
            txt_pass2.setEchoChar((char) 0);

        } else {
            txt_pass2.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox3jCheckBox1ActionPerformed

    private void btn_Insert1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Insert1ActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url, user, pass);
            String sql = "insert into login"
                    + "(username,Name,email,password)"
                    + "values(?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, Id4.getText());
            pst.setString(2, Id5.getText());
            pst.setString(3, Id6.getText());
            pst.setString(4, txt_pass2.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Insert sucessfully");
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }


    }//GEN-LAST:event_btn_Insert1ActionPerformed

    private void jCheckBox4jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4jCheckBox1ActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_btn_updateActionPerformed

    private void txt_searchidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchidActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel1MouseClicked

    private void jPanel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseEntered
        // TODO add your handling code here:
        sColor(jPanel10);
    }//GEN-LAST:event_jPanel10MouseEntered

    private void jPanel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseExited
        // TODO add your handling code here:
        rColor(jPanel10);
    }//GEN-LAST:event_jPanel10MouseExited

    private void jPanel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MousePressed
        // TODO add your handling code here:
        AdminHome Sh = new AdminHome();
        Sh.setVisible(true);
        Sh.pack();
        Sh.setLocationRelativeTo(null);
        Sh.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jPanel10MousePressed

    private void txt_searchidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchidKeyReleased
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url, user, pass);
            String sql = "select * from login where username=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, txt_searchid.getText());

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                String add1 = rs.getString("username");
                Id1.setText(add1);
                String add2 = rs.getString("Name");
                Id2.setText(add2);
                String add3 = rs.getString("email");
                Id3.setText(add3);
                String add4 = rs.getString("password");
                txt_pass1.setText(add4);
                

                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Update sucessfully");

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_txt_searchidKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuperAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuperAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuperAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuperAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuperAdmin().setVisible(true);
            }
        });
    }

    public void sColor(JPanel panel) {

        panel.setBackground(new java.awt.Color(25, 181, 254));
    }

    public void rColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(45, 118, 232));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Addlib_panel;
    private javax.swing.JPanel Editlib_panel;
    private javax.swing.JTextField Id1;
    private javax.swing.JTextField Id2;
    private javax.swing.JTextField Id3;
    private javax.swing.JTextField Id4;
    private javax.swing.JTextField Id5;
    private javax.swing.JTextField Id6;
    private javax.swing.JButton btn_Insert1;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel exit;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField txt_pass1;
    private javax.swing.JPasswordField txt_pass2;
    private javax.swing.JPasswordField txt_pass3;
    private javax.swing.JTextField txt_searchid;
    // End of variables declaration//GEN-END:variables
}
